### ISSUE TITLE
dbma-cli-single-instance --port=3306  install命令报错/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'

### ISSUE THREAD

**Issue by TimeIsGoOn** [Neeky/dbm-agent#1]
服务器信息

root@VM-0-7-ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

---

### 配置信息
root@VM-0-7-ubuntu:~# tree /usr/local/dbm-agent/
/usr/local/dbm-agent/
├── etc
│   ├── dbma.cnf
│   ├── init-users.sql
│   └── templates
│       ├── create-innodb-cluster.js
│       ├── init-users.sql.jinja
│       ├── mysql-8.0-init-only.jinja
│       ├── mysql-8.0.17.cnf.jinja
│       ├── mysql-8.0.18.cnf.jinja
│       └── mysqld.service.jinja
├── logs
└── pkg
    ├── download_mysql-8.0.sh　//这是我自己写的下载shell
    ├── mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz
    └── mysql-shell-8.0.18-linux-glibc2.12-x86-64bit.tar.gz

4 directories, 11 files

---
### 报错信息

root@VM-0-7-ubuntu:~# dbma-cli-single-instance --port=3306 install 
2019-11-20 13:38:51,723 - dbm-agent.dbma.mysqldeploy.SingleInstanceInstaller.install - im - INFO - 1115 - execute checkings for install mysql
/usr/bin/python3: Relink `/lib/x86_64-linux-gnu/libnss_systemd.so.2' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)

`

**Comment by TimeIsGoOn** [comment]
补上那个download_mysql-8.0.sh的内容
```
root@VM-0-7-ubuntu:/usr/local/dbm-agent# cd pkg/

root@VM-0-7-ubuntu:/usr/local/dbm-agent/pkg# ls
download_mysql-8.0.sh  mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz  mysql-shell-8.0.18-linux-glibc2.12-x86-64bit.tar.gz
root@VM-0-7-ubuntu:/usr/local/dbm-agent/pkg# pwd
/usr/local/dbm-agent/pkg

root@VM-0-7-ubuntu:/usr/local/dbm-agent/pkg# cat download_mysql-8.0.sh 

wget https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell-8.0.18-linux-glibc2.12-x86-64bit.tar.gz

wget https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz


```

**Comment by Neeky** [comment]
dbm-agent 一开始设计的时候就是面向 centos-7 与 centos-8 的，作为一个只有一个开发都的项目，目前没有太多的精力来做 ubuntu 上的兼容。

你可以在 centos-7.6 上检验一下
