### ISSUE TITLE
Could not find a version that satisfies the requirement redis>=4.5.4 (from dbm-agent)

### ISSUE THREAD

**Issue by deprecate98** [Neeky/dbm-agent#11]
执行pip3 install dbm-agent报：
Could not find a version that satisfies the requirement redis>=4.5.4 (from dbm-agent)

**Comment by Neeky** [comment]
1、大佬这个安装会报错吗？
pip3 install -i https://mirrors.aliyun.com/pypi/simple  dbm-agent

**Comment by Neeky** [comment]
是有 redis-4.5.4 这个版本的，只是这个版本比较新

pip3 install redis==4.5.4
Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple
Collecting redis==4.5.4
  Downloading https://mirrors.cloud.tencent.com/pypi/packages/b5/d4/ef474a49ec5821f3155c5de2d37ddcc4a497e2500cd16d4a9e51ce02030d/redis-4.5.4-py3-none-any.whl (238 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.9/238.9 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: async-timeout>=4.0.2 in ./softwares/python/lib/python3.11/site-packages (from redis==4.5.4) (4.0.2)
Installing collected packages: redis
Successfully installed redis-4.5.4
