### ISSUE TITLE
请问 dbm-monitor-gateway 程序在哪里？

### ISSUE THREAD

**Issue by stone2014** [Neeky/dbm-agent#12]
请问大佬 dbm-monitor-gateway 程序在哪里可以找到？谢谢。

**Comment by Neeky** [comment]
比较老的版本才有， dbm-agent-8.22.0 。  pip3 install dbm-agent==8.22.0 这样可以安装上。

**Comment by Neeky** [comment]
如果你们确实有强依赖的话，后面我也可以把它加回去。

**Comment by stone2014** [comment]
收到，多谢大哥的解答，已找到这个程序。dbm-monitor-gateway 这个程序还是非常好的，如果加回去会更好。谢谢
