### ISSUE TITLE
配置 innodb-cluster 报错

### ISSUE THREAD

**Issue by pandakill-git** [Neeky/dbm-agent#3]
mysqlsh --uri innodbclusteradmin@127.0.0.1:3306 --password=dbma@0352 < /usr/local/dbm-agent/etc/templates/create-innodb-cluster.js 
WARNING: Using a password on the command line interface can be insecure.
A new InnoDB cluster will be created based on the existing replication group on instance '127.0.0.1:3306'.

Creating InnoDB cluster 'production' on 'mysql-one:3306'...

Adding Seed Instance...

Adding Instance 'mysql-three:3306'...
Adding Instance 'mysql-one:3306'...
Adding Instance 'mysql-two:3306'...
Resetting distributed recovery credentials across the cluster...
Dba.createCluster: mysql-one:3306: Access denied; you need SYSTEM_VARIABLES_ADMIN and PERSIST_RO_VARIABLES_ADMIN privileges for this operation (RuntimeError)
 at STDIN:2:18
in var cluster = dba.createCluster('production', { adoptFromGR: true });

**Comment by pandakill-git** [comment]
难道是host导致的？

`[root@mysql-one ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

10.25.96.4 mysql-one
10.25.96.5 mysql-two
10.25.96.6 mysql-three`

**Comment by Neeky** [comment]
1、看样子是权限少了，这个权限第一次看到有可能是新版本引入的，你的版本是多少？
2、方便的话也给一下其它信息方便我分析问题 2.1 操作系统 2.2 dbm-agent 版本 2.3 /usr/local/dbm-agent/etc/init-users.sql 这个文件

**Comment by pandakill-git** [comment]
1. mysql  Ver 8.0.19 for linux-glibc2.12 on x86_64 (MySQL Community Server - GPL)

2.1 CentOS Linux release 7.7.1908 (Core)

2.2 dbma-agent 0.8.6

2.3
[root@mysql-one ~]# cat /usr/local/dbm-agent/etc/init-users.sql
set @@sql_log_bin=0;

alter user root@'localhost' identified by 'dbma@0352';
create user root@'127.0.0.1' identified by 'dbma@0352';
grant all on *.* to root@'127.0.0.1' with grant option;

create user dbma@'127.0.0.1' identified by 'dbma@0352';
grant all on *.* to dbma@'127.0.0.1' with grant option;

-- clone
create user 'cloneuser'@'127.0.0.1' identified by 'dbma@0352';
grant clone_admin,system_variables_admin,backup_admin on *.* to 'cloneuser'@'127.0.0.1';
create user 'cloneuser'@'localhost' identified by 'dbma@0352';
grant clone_admin,system_variables_admin,backup_admin on *.* to 'cloneuser'@'localhost';
create user 'cloneuser'@'%' identified by 'dbma@0352';
grant backup_admin on *.* to 'cloneuser'@'%';

-- replication
create user 'repluser'@'%' identified by 'dbma@0352';
grant replication slave,replication client,backup_admin,replication_slave_admin,group_replication_admin on *.* to 'repluser'@'%';

-- monitor
create user monitor@'127.0.0.1' identified by 'dbma@0352';
grant replication client,process on *.* to monitor@'127.0.0.1';
grant select on performance_schema.* to monitor@'127.0.0.1';

-- innodb cluster admin user
create user innodbclusteradmin@'%' identified by 'dbma@0352';
grant reload, shutdown, process, file, select, super, replication slave, replication client, create user on *.* to innodbclusteradmin@'%' with grant option;
grant all on mysql_innodb_cluster_metadata.* to innodbclusteradmin@'%' with grant option;
grant insert, update, delete on mysql.* to innodbclusteradmin@'%' with grant option;
grant select on performance_schema.global_status to innodbclusteradmin@'%' with grant option;
grant select on performance_schema.replication_applier_configuration to innodbclusteradmin@'%' with grant option;
grant select on performance_schema.replication_applier_status to innodbclusteradmin@'%' with grant option;
grant select on performance_schema.replication_applier_status_by_coordinator to innodbclusteradmin@'%' with grant option;
grant select on performance_schema.replication_applier_status_by_worker to innodbclusteradmin@'%' with grant option;
grant select on performance_schema.replication_connection_configuration to innodbclusteradmin@'%' with grant option;
grant select on performance_schema.replication_connection_status to innodbclusteradmin@'%' with grant option;
grant select on performance_schema.replication_group_member_stats to innodbclusteradmin@'%' with grant option;
grant select on performance_schema.replication_group_members to innodbclusteradmin@'%' with grant option;
grant select on performance_schema.threads to innodbclusteradmin@'%' with grant option;

-- mysqldump
create user mysqldump@'127.0.0.1' identified by 'dbma@0352';
grant select on *.* to mysqldump@'127.0.0.1';
grant show view on *.* to mysqldump@'127.0.0.1';
grant lock tables on *.* to mysqldump@'127.0.0.1';
grant trigger on *.* to mysqldump@'127.0.0.1';
grant super,replication client on *.* to 'mysqldump'@'127.0.0.1';
grant reload,event on *.* to 'mysqldump'@'127.0.0.1';

create user mysqldump@'localhost' identified by 'dbma@0352';
grant select on *.* to mysqldump@'localhost';
grant show view on *.* to mysqldump@'localhost';
grant lock tables on *.* to mysqldump@'localhost';
grant trigger on *.* to mysqldump@'localhost';
grant super,replication client on *.* to 'mysqldump'@'localhost';
grant reload,event on *.* to 'mysqldump'@'localhost';


-- mysqlbackup
create user mysqlbackup@'127.0.0.1' identified by 'dbma@0352';
grant select on *.* to 'mysqlbackup'@'127.0.0.1';
grant backup_admin on *.* to 'mysqlbackup'@'127.0.0.1';
grant select on performance_schema.variables_info to 'mysqlbackup'@'127.0.0.1';
grant select on performance_schema.log_status to 'mysqlbackup'@'127.0.0.1';
grant reload on *.* to 'mysqlbackup'@'127.0.0.1';
grant create, insert, drop, update on mysql.backup_progress to 'mysqlbackup'@'127.0.0.1';
grant create, insert, drop, update, select, alter on mysql.backup_history TO 'mysqlbackup'@'127.0.0.1';
grant replication client on *.* to 'mysqlbackup'@'127.0.0.1';
grant super on *.* to 'mysqlbackup'@'127.0.0.1';
grant process on *.* to 'mysqlbackup'@'127.0.0.1';
grant select on performance_schema.replication_group_members to 'mysqlbackup'@'127.0.0.1';
grant alter on mysql.backup_progress to 'mysqlbackup'@'127.0.0.1';
grant create, insert, drop on mysql.backup_progress_old to 'mysqlbackup'@'127.0.0.1';
grant create, insert, drop, alter on mysql.backup_progress_new to 'mysqlbackup'@'127.0.0.1';
grant create, insert, drop on mysql.backup_history_old to 'mysqlbackup'@'127.0.0.1';
grant create, insert, drop, alter on mysql.backup_history_new to 'mysqlbackup'@'127.0.0.1';
grant lock tables, select, create, drop, file on *.* to 'mysqlbackup'@'127.0.0.1';
grant create, insert, drop, update on mysql.backup_sbt_history to 'mysqlbackup'@'127.0.0.1'; 
grant encryption_key_admin on *.* to 'mysqlbackup'@'127.0.0.1';
-- grant seelct on non-InnoDB_tbl to 'mysqlbackup'@'127.0.0.1';
grant innodb_redo_log_archive on *.* to 'mysqlbackup'@'127.0.0.1';

create user mysqlbackup@'localhost' identified by 'dbma@0352';
grant select on *.* to 'mysqlbackup'@'localhost';
grant backup_admin on *.* to 'mysqlbackup'@'localhost';
grant select on performance_schema.variables_info to 'mysqlbackup'@'localhost';
grant select on performance_schema.log_status to 'mysqlbackup'@'localhost';
grant reload on *.* to 'mysqlbackup'@'localhost';
grant create, insert, drop, update on mysql.backup_progress to 'mysqlbackup'@'localhost';
grant create, insert, drop, update, select, alter on mysql.backup_history TO 'mysqlbackup'@'localhost';
grant replication client on *.* to 'mysqlbackup'@'localhost';
grant super on *.* to 'mysqlbackup'@'localhost';
grant process on *.* to 'mysqlbackup'@'localhost';
grant select on performance_schema.replication_group_members to 'mysqlbackup'@'localhost';
grant alter on mysql.backup_progress to 'mysqlbackup'@'localhost';
grant create, insert, drop on mysql.backup_progress_old to 'mysqlbackup'@'localhost';
grant create, insert, drop, alter on mysql.backup_progress_new to 'mysqlbackup'@'localhost';
grant create, insert, drop on mysql.backup_history_old to 'mysqlbackup'@'localhost';
grant create, insert, drop, alter on mysql.backup_history_new to 'mysqlbackup'@'localhost';
grant lock tables, select, create, drop, file on *.* to 'mysqlbackup'@'localhost';
grant create, insert, drop, update on mysql.backup_sbt_history to 'mysqlbackup'@'localhost'; 
grant encryption_key_admin on *.* to 'mysqlbackup'@'localhost';
-- grant seelct on non-InnoDB_tbl to 'mysqlbackup'@'localhost';
grant innodb_redo_log_archive on *.* to 'mysqlbackup'@'localhost';

set @@sql_log_bin=1;

**Comment by Neeky** [comment]
dbm-agent-0.8.7 修复了这个问题，因为就是 mysql-8.0.19 引入了新的权限，我在这个版本加上了。

1、升级软件包 pip3 install dbm-agent==0.8.7

2、升级配置文件 dbm-agent upgrade                                                             
2020-03-02 10:15:12,756 INFO going to upgrade dbm-agent
2020-03-02 10:15:12,756 INFO backup etc/templates
2020-03-02 10:15:12,757 INFO create new etc/templates
2020-03-02 10:15:12,768 INFO prepare rende init-sql-file /usr/local/dbm-agent/etc/init-users.sql
2020-03-02 10:15:12,769 INFO init-sql-file render complete
2020-03-02 10:15:12,769 DEBUG sudo context config dbm-monitor-gateway
2020-03-02 10:15:12,971 INFO monitor-gateway render complete
2020-03-02 10:15:12,971 DEBUG sudo context config dbm-backup-proxy
2020-03-02 10:15:13,116 INFO monitor-gateway render complete
2020-03-02 10:15:13,128 INFO upgrade complete

3、更新 8.0.19 版本上的用户权限
mysql -uroot -pdbma@0352 -h127.0.0.1 -P3306 --force /usr/local/dbm-agent/etc/init-users.sql



总的来讲就是这一句：
grant system_variables_admin,persist_ro_variables_admin on *.* to innodbclusteradmin@'%';
