### ISSUE TITLE
MGR 如何扩容咦？

### ISSUE THREAD

**Issue by pandakill-git** [Neeky/dbm-agent#5]
微信交流群加不上，想了解一下后期如何扩容MGR

**Comment by Neeky** [comment]
dbma-cli-build-mgr --port=3306 --max-mem=128 --members=192.168.100.101,192.168.100.102,192.168.100.103 build-mgr   把新的主机加到 --members 后面就行了。

**Comment by pandakill-git** [comment]
就是在最新的那台主机，执行的命令里面加自身的IP就行啦？

**Comment by Neeky** [comment]
是的、前期的准备你要做好、比如 DNS 解析，防火墙的设置等待

**Comment by Neeky** [comment]
是的、前期的准备你要做好、比如 DNS 解析，防火墙的设置等等。
