### ISSUE TITLE
testunit syntax error

### ISSUE THREAD

**Issue by martin-ly** [Neeky/dbm-agent#8]
`[root@slave1 dbm-agent-master]# python3 --version
Python 3.8.0
[root@slave1 dbm-agent-master]# bash autotest.sh 
useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.
Creating mailbox file: File exists
.............E.........useradd: user 'mysql' already exists
..............s
======================================================================
ERROR: test_dbmaconfig (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dbmaconfig
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/root/dbm-agent-master/tests/test_dbmaconfig.py", line 10
    class TestConfigMixinTestCase(unittest.TestCase)
                                                   ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 38 tests in 7.626s

FAILED (errors=1, skipped=1)
[root@slave1 dbm-agent-master]# 
`

**Comment by Neeky** [comment]
bash autotest.sh 是用于在 docker 容器中进行的，我们约定一个 docker 容器在测试完成之后就不在使用，主要原因是运行测试用的过程中会创建用户，文件，目录，等等内容。 不想一一的清理，所以一个容器只用一次。

**Comment by Neeky** [comment]
Fixed

**Comment by Neeky** [comment]
bash autotest.sh 
.....................................
----------------------------------------------------------------------
Ran 37 tests in 0.390s

OK
